# Generated by Django 6.0 on 2025-12-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('buy_url', models.URLField(help_text='BuyMeACoffee / Project purchase link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
